sudo: false
language: go
go:
  - 1.10.x
  - 1.11.x
  - 1.12.x

# Skip the install step. Don't `go get` dependencies. Only build with the
# code in vendor/
install: true

# Only clone the most recent commit.
git:
  depth: 1

before_script:
   go install github.com/mitchellh/gox

script:
  - make
  - make test
