language: go
go:
  - 1.11.x
  - 1.12.x

sudo: false

# Force-enable Go modules..
# This will be unnecessary when Go 1.13 lands.
env:
  - GO111MODULE=on

# Only clone the most recent commit.
git:
  depth: 1

before_script:
  - go install github.com/mitchellh/gox
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - make
  - make test
  - make lint
  - make vet
