language: go

# Only clone the most recent commit.
git:
  depth: 1

sudo: false

matrix:
  allow_failures:
    - go: 'master'
  fast_finish: true
  include:
    # Supported versions of Go: https://golang.org/dl/
    - go: "1.12.x"
    - go: "1.13.x"
    - go: master

env:
  global:
    - GO111MODULE=on

notifications:
  email: false

before_script:
  - go install github.com/mitchellh/gox
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - make
  - make test
  - make lint
  - make vet
