language: go

# GO111MODULE=on forces-enable Go modules.
# This is no more necessary with Go 1.13.
matrix:
  include:
  - go: 1.13.x
  - go: 1.12.x
    env: GO111MODULE=on

sudo: false

# Only clone the most recent commit.
git:
  depth: 1

before_script:
  - go install github.com/mitchellh/gox
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - make
  - make test
  - make lint
  - make vet
