language: go

# Force-enable Go modules.
# This be unnecessary when Go 1.14 lands.
env:
  GO111MODULE=on

go:
  - 1.12.x
  - 1.13.x
  - master

# Only clone the most recent commit.
git:
  depth: 1

sudo: false

matrix:
  allow_failures:
    - go: 'master'
  fast_finish: true

notifications:
  email: false

before_script:
  - go install github.com/mitchellh/gox
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - make
  - make test
  - make lint
  - make vet
