sudo: false
language: go
go:
  - 1.10.x
  - 1.11.x
  - 1.12.x

# Only clone the most recent commit.
git:
  depth: 1

before_script:
   go install github.com/mitchellh/gox

script:
  - make
  - make test
