# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/hashicorp/vault"
  branch = "master"

[[constraint]]
  name = "github.com/mitchellh/cli"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-test/deep"
  version = "v1.0.3"

[[constraint]]
  name = "github.com/hako/durafmt"
  version = "1.0.0"

[prune]
  go-tests = true
  unused-packages = true
