# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "0.11.1"

[[constraint]]
  name = "github.com/mitchellh/cli"
  version = "1.0.0"

[prune]
  go-tests = true
  unused-packages = true
